// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackSource } from "./TrackSource";
import type { Variant } from "./Variant";

export type LibraryEntry = { id?: number, parentId?: number, variant: Variant, name: string, image?: Array<number>, playedAt?: string, sortKey: number, children?: Array<LibraryEntry>, trackSource?: TrackSource, parentName?: string, parentImage?: Array<number>, };
