// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SpotifyConfig { clientId: string, secretKey: string, refreshToken?: string, accessToken?: string, expiredAt?: string, username?: string, password?: string, }