// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackSource = { id?: number, libraryEntryId: number, title: string, url?: string, file?: Array<number>, spotifyId?: string, spotifyType?: string, };
