[config]
default_to_workspace = false

[tasks.build-admin-interface-ui]
cwd = "./admin_interface/web_ui"
script = "npm run build"

[tasks.build-image-docker]
script = "docker build -t cross_compile ."

[tasks.build-image-podman]
script = "podman build -t cross_compile ."

[tasks.build-binaries-docker]
script = "docker run -ti -u $(id -u):$(id -g) -v .:/project/tinyghettobox/ -v /mnt/h/Data/projects/kira:/project/kira -v ~/.cargo:/.cargo cross_compile"

[tasks.build-binaries-podman]
script = "podman run -ti -u $(id -u):$(id -g) -v .:/project/tinyghettobox/ -v /mnt/h/Data/projects/kira:/project/kira -v ~/.cargo:/.cargo cross_compile"

[tasks.build-deb]
script = "docker run -ti -u $(id -u):$(id -g) -v .:/project/tinyghettobox/ -v /mnt/h/Data/projects/kira:/project/kira -v ~/.cargo:/.cargo cross_compile make -C debian"
