[General]
arch=arm64
noauth=false
unpack=true
cleanup=true
bootstrap=Noble
aptsources=Noble


; [Noble]
; packages=librsvg2-dev libglib2.0-dev libgtk-4-dev libasound2-dev libdbus-1-dev x11proto-dev build-essential libbsd-dev libssl-dev libpulse0
; source=http://ports.ubuntu.com/ubuntu-ports/
; keyring=ubuntu-keyring
; suite=oracular
; components=main restricted universe multiverse

[Noble]
packages=librsvg2-dev libglib2.0-dev libgtk-4-dev libasound2-dev libdbus-1-dev x11proto-dev build-essential libbsd-dev libssl-dev libpulse0
source=http://http.debian.net/debian
keyring=debian-archive-keyring
suite=bookworm
components=main contrib non-free
