[package]
name = "player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
base64 = "0.22.1"
chrono = "0.4.31"
database = { path = "../database" }
kira = { version = "0.10.2", features = ["cpal"] }
kira-remote-stream = { path = "../kira_remote_stream" }
reqwest = { version = "0.12.15", features = ["json"] }
symphonia = "0.5.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.35.1", features = ["rt-multi-thread", "full", "tracing"] }
tracing = "0.1.40"
librespot = { git = "https://github.com/librespot-org/librespot", rev = "5440c4d385302ab35550a3551365a0b86f8c72ad", default-features = false, features = ["with-libmdns", "native-tls"] }

[target.'cfg(target_os = "windows")'.dependencies]
librespot = { git = "https://github.com/librespot-org/librespot", rev = "5440c4d385302ab35550a3551365a0b86f8c72ad", default-features = false, features = ["rodio-backend", "with-libmdns", "native-tls"] }

[target.'cfg(target_os = "linux")'.dependencies]
librespot = { git = "https://github.com/librespot-org/librespot", rev = "5440c4d385302ab35550a3551365a0b86f8c72ad", default-features = false, features = ["pulseaudio-backend", "with-libmdns", "native-tls"] }