[package]
name = "tinyghettobox"
description = "User and admin interface for tiny ghetto box"
version = "0.1.0"
edition = "2021"

# dummy bin needed to prevent errors from cargo
[[bin]]
name = "dummy"
path = "./dummy.rs"

[package.metadata.deb]
maintainer = "Thomas Schlage <t.schlage@gmx.net>"
license-file = ["../LICENSE", "4"]
extended-description = """\
User and admin interface and the setup for the tiny ghetto box."""
depends = "libgtk-4.0 (>=4.8.0)"
section = "base"
priority = "important"
maintainer-scripts = "./DEBIAN"
systemd-units = [
    { unit-name = "spotifyd", unit-scripts = "etc/systemd/system", enable = true },
    { unit-name = "tgb.admin-interface", unit-scripts = "etc/systemd/system", enable = true },
    { unit-name = "tgb.user-interface", unit-scripts = "etc/systemd/system", enable = true }
]
assets = [
    ["../target/aarch64-unknown-linux-gnu/release/admin_interface_server", "srv/tinyghettobox/admin_interface", "755"],
    ["../target/aarch64-unknown-linux-gnu/release/user_interface", "srv/tinyghettobox/user_interface", "755"],
    ["../target/aarch64-unknown-linux-gnu/release/spotifyd", "srv/tinyghettobox/spotifyd", "755"],
    ["../admin_interface/web_ui/dist/**/*", "srv/admin_interface_ui/", "644"],
    ["./etc/spotifyd/spotifyd.conf", "etc/spotifyd/spotifyd.conf", "644"],
    ["../tinyghettobox.sqlite", "srv/tinyghettobox/tinyghettobox.sqlite", "644"]
]