[package]
name = "tinyghettobox"
description = "User and admin interface for tiny ghetto box"
version = "0.1.0"
edition = "2021"

# dummy bin needed to prevent errors from cargo
[[bin]]
name = "dummy"
path = "./dummy.rs"

[package.metadata.deb]
maintainer = "Thomas Schlage <t.schlage@gmx.net>"
copyright = "2024, Thomas Schlage <t.schlage@gmx.net>"
license-file = ["../LICENSE", "4"]
extended-description = """\
User and admin interface and the setup for the tiny ghetto box."""
depends = "libgtk-4.0 (>=4.8.0)"
section = "base"
priority = "important"
maintainer-scripts = "./DEBIAN"
systemd-units = [
    { unit-name = "splashscreen", unit-scripts = "usr/lib/systemd/system", enable = true },
    { unit-name = "spotifyd", unit-scripts = "usr/lib/systemd/system", enable = true },
    { unit-name = "tgb.admin-interface", unit-scripts = "usr/lib/systemd/system", enable = true },
    { unit-name = "tgb.user-interface", unit-scripts = "usr/lib/systemd/system", enable = true }
]
assets = [
    ["../target/aarch64-unknown-linux-gnu/release/admin_interface_server", "usr/bin/tinyghettobox/admin_interface", "755"],
    ["../target/aarch64-unknown-linux-gnu/release/user_interface", "usr/bin/tinyghettobox/user_interface", "755"],
    ["../target/aarch64-unknown-linux-gnu/release/spotifyd", "usr/bin/tinyghettobox/spotifyd", "755"],
    ["../admin_interface/web_ui/dist/**/*", "var/www/admin_interface/web_ui/", "644"],
    ["./etc/spotifyd/spotifyd.conf", "etc/spotifyd/spotifyd.conf", "644"],
#    ["./etc/asound.conf", "etc/asound.conf", "755"],
#    ["./usr/share/fonts/*", "usr/share/fonts", "755"],
#    ["./usr/lib/systemd/system-shutdown/poweroff.sh", "usr/lib/systemd/system-shutdown/poweroff.sh", "755"],
#    ["./var/lib/dietpi/postboot.d/off_trigger.sh", "var/lib/dietpi/postboot.d/off_trigger.sh", "755"],
    ["./var/lib/tinyghettobox/tinyghettobox.sqlite", "var/lib/tinyghettobox/tinyghettobox.sqlite", "644"],
    ["../README.md", "usr/share/doc/cargo-deb/README", "644"],
]