#!/bin/bash

# Stop the systemd services
systemctl stop tgb.user-interface.service
systemctl stop tgb.admin-interface.service

# Disable the systemd services
systemctl disable tgb.user-interface.service
systemctl disable tgb.admin-interface.service

exit 0