[package]
name = "user_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = { version = "1.13.1" }
tokio = { version = "1.47.1", features = ["full"] }
chrono = "0.4"
image = "*"
async-trait = "0.1.80"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
database = { path = "../database" }
player = { path = "../player" }

[build-dependencies]
slint-build = { version = "1.13.1", features = ["default"] }
